//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Groups = new HashSet<UserGroup>();
            this.Roles = new HashSet<UserRole>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<UserGroup> Groups { get; set; }
        public virtual ICollection<UserRole> Roles { get; set; }
    }
}
